In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
# DN = 'C://work/dev/python/progs/texts/sec_bert/'
DN = '/home/jovyan/work/sec_bert/'

import os
os.chdir(DN)

# Start File

In [ ]:
%run src/ttp/train_eval_model.py dvc_pipes/ttp/params_ttp.yaml

In [6]:
%debug

> /home/jovyan/work/sec_bert/src/funcs.py(210)<listcomp>()
    208         # import pdb;pdb.set_trace()
    209         pred = (proba>thresh).astype(int)
--> 210         p, r, f1, sup = [it[1] for it in precision_recall_fscore_support(y_true, pred)]
    211 
    212         res_metrics_df = pd.DataFrame({'precision':p, 'recall':r, 'f1':f1, 'sup':sup}, index=[thresh])



ipdb>  y_true


*** NameError: name 'y_true' is not defined


ipdb>  pred


*** NameError: name 'pred' is not defined


ipdb>  l


    205     if len(thresh_space_l)==0:
    206         thresh_space_l = np.arange(0.05, 0.95, 0.05)
    207     for thresh in thresh_space_l:
    208         # import pdb;pdb.set_trace()
    209         pred = (proba>thresh).astype(int)
--> 210         p, r, f1, sup = [it[1] for it in precision_recall_fscore_support(y_true, pred)]
    211 
    212         res_metrics_df = pd.DataFrame({'precision':p, 'recall':r, 'f1':f1, 'sup':sup}, index=[thresh])
    213         res_metrics_l.append(res_metrics_df)
    214     res_df = pd.concat([it for it in res_metrics_l], axis=0)
    215     thresh = res_df.index[res_df[opt_metric].argmax()].round(3)



ipdb>  u


> /home/jovyan/work/sec_bert/src/funcs.py(210)get_pred_thresh()
    208         # import pdb;pdb.set_trace()
    209         pred = (proba>thresh).astype(int)
--> 210         p, r, f1, sup = [it[1] for it in precision_recall_fscore_support(y_true, pred)]
    211 
    212         res_metrics_df = pd.DataFrame({'precision':p, 'recall':r, 'f1':f1, 'sup':sup}, index=[thresh])



ipdb>  y_true


array([0, 0, 0, ..., 0, 0, 0])


ipdb>  pred


array([0, 0, 0, ..., 0, 0, 0])


ipdb>  precision_recall_fscore_support(y_true, pred)


(array([1.]), array([1.]), array([1.]), array([5119]))


ipdb>  y_true, proba


(array([0, 0, 0, ..., 0, 0, 0]), array([4.09134237e-06, 9.25268387e-05, 4.72146727e-05, ...,
       1.74652138e-03, 8.58826392e-04, 1.12189642e-04]))


ipdb>  y_true.sum()


0


ipdb>  


0


ipdb>  q


# DVC

- dvc exp run -S val_only_proc=false

- dvc exp show --drop .* --keep 'Experiment|кол1|кол2' --rev commit